# Generated by Django 4.2.7 on 2024-03-06 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_studentuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentUser',
        ),
    ]
