# Generated by Django 4.2.7 on 2024-03-06 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
