# Generated by Django 4.2.7 on 2023-12-04 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_userone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userone',
            new_name='User',
        ),
    ]
